### ISSUE TITLE
Incorrect percentages on Modes

### ISSUE THREAD

**Issue by eldooned** [iBotPeaches/LeafApp_Infinite#1007]
On the modes window, when the same map / mode is on both sides, it adds up to 110% instead of 100%.

![image](https://github.com/iBotPeaches/LeafApp_Infinite/assets/6815544/ec58f16c-14c8-4600-b77a-a01c2a79ade2)

https://leafapp.co/player/Noodle2132/modes - Profile where the issue is occurring

**Comment by iBotPeaches** [comment]
@eldooned am I missing which one is wrong?

 * Solitude KoTH - 50.00 + 50.00 = 100
 * Live Fire Slayer - 53.85 + 46.15 = 100
 * Empyrean CTF - 56.52 + 43.48 = 100

Just looking at your image there.

**Comment by eldooned** [comment]
Sorry it was late in Europe when I sent this. Maybe I should get some sleep instead of feeding on Halo. Apologies for wasting your time.

**Comment by iBotPeaches** [comment]
No worries. I was paranoid building this that this exact mistake might happen, so was surprised when I saw this.
