### ISSUE TITLE
“Account Private”

### ISSUE THREAD

**Issue by Craibzz** [iBotPeaches/LeafApp_Infinite#1141]
I like to check my stats on Leafapp.co but it says my account settings are set to private. I checked with Halo infinite settings and they are public, as well as HaloWaypoint, but my statistics aren’t viewable. It seems it’s an issue with Leafapp not updating properly or verifying the settings.

**Comment by iBotPeaches** [comment]
Have a gamertag I can peek against?

**Comment by iBotPeaches** [comment]
We solved on Discord. Closing.
