### ISSUE TITLE
Fix gamertags with spaces it seems

### ISSUE THREAD

**Issue by Computurtle** [iBotPeaches/LeafApp_Infinite#854]
https://leafapp.co/player/ash%20n%20reece

This gamertag is unable to be requested. Unsure why.

**Comment by iBotPeaches** [comment]
Thanks - it seems in that user's case that they renamed. So when we try and pull their stats - it no longer exists to find. At some point in the future I wish to detect these renames utilizing XUIDs to pull the new gamertag, but its a bit more effort to do all of that.
